package property;

import static top.desky.example.drools.some.BaseCommon.printInfo;

rule "dateEffective1"
date-effective "2018-04-14"
    when
    then
        printInfo("命中的规则名：" + drools.getRule().getName());
end

rule "dateEffective2"
date-effective "2018-04-15"
date-expires "2018-04-18"
    when
    then
        printInfo("命中的规则名：" + drools.getRule().getName());
end

rule "dateEffective3"
date-effective "2018-04-16"
    when
    then
        printInfo("命中的规则名：" + drools.getRule().getName());
end