package property;

import static top.desky.example.drools.some.BaseCommon.printInfo;

rule "duration1"
duration 1
    when
    then
        printInfo("命中的规则名：" + drools.getRule().getName());
end

rule "duration2"
duration 3
    when
    then
        printInfo("命中的规则名：" + drools.getRule().getName());
end

rule "duration3"
duration 2
    when
    then
        printInfo("命中的规则名：" + drools.getRule().getName());
end